# Copyright 2025 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE.solderpad for details.
# SPDX-License-Identifier: SHL-0.51
#
# Sergio Mazzola <smazzola@iis.ee.ethz.ch>
# Magna Mishra   < Updates for Wakelet's integration with Croc>

# Changes:
# 1. Remove JTAG test support - CVE2 firmware now drives tests 
# 2. Include rule for header generation for binaries compiled for CVE2
# 3. Flow: CVE2 makefile invokes snitch from bender dependancy -> .c compiled in snitch -> create .bin binary -> generate header 

WL_SW_DIR = $(WL_ROOT)/sw

# Tooling
#GCC_ROOT ?= $(dir $(shell which riscv32-unknown-elf-gcc))
GCC_ROOT= /usr/pack/riscv-1.0-kgf/default/bin


CC      := $(GCC_ROOT)/riscv32-unknown-elf-gcc
OBJCOPY := $(GCC_ROOT)/riscv32-unknown-elf-objcopy
OBJDUMP := $(GCC_ROOT)/riscv32-unknown-elf-objdump

################################
# Hw parameters from config.mk #
################################

# Add defines to compilation
WL_SW_HWDEFS := -DDATA_MEM_NUMBYTES=$(shell expr $(DATA_MEM_NUMWORDS) \* 4)
WL_SW_HWDEFS += -DINSTR_MEM_NUMBYTES=$(shell expr $(INSTR_MEM_NUMWORDS) \* 4)

WL_SW_HWDEFS += -DACT_MEM_NUMBANKS=$(ACT_MEM_NUMBANKS)
WL_SW_HWDEFS += -DACT_MEM_NUMBANKWORDS=$(ACT_MEM_NUMBANKWORDS)
WL_SW_HWDEFS += -DACT_MEM_NUMELEMWORD=$(ACT_MEM_NUMELEMWORD)
WL_SW_HWDEFS += -DACT_MEM_ELEMWIDTH=$(ACT_MEM_ELEMWIDTH)
WL_SW_HWDEFS += -DACT_MEM_WORDWIDTH=$(shell expr $(ACT_MEM_NUMELEMWORD) \* $(ACT_MEM_ELEMWIDTH) / 8)

##########
# Set up #
##########

MARCH ?= rv32em

WL_SW_FLAGS += -DOT_PLATFORM_RV32 -march=$(MARCH) -mabi=ilp32e -mstrict-align -O2 -Wall -Wextra -static -ffunction-sections -fdata-sections -fuse-linker-plugin -flto -Wl,-flto $(WL_SW_HWDEFS)
CC_LD_FLAGS ?= $(WL_SW_FLAGS) -nostartfiles -Wl,--gc-sections
CC_FLAGS ?= $(WL_SW_FLAGS) -ggdb -mcmodel=medany -mexplicit-relocs -fno-builtin -fverbose-asm -pipe -MMD -MP

WL_SW_INCL ?= -I$(WL_SW_DIR)/runtime/include -I$(WL_SW_DIR)/hal/include
WL_SW_LIBS = 

# Other sources
LINKER_SCRIPT = $(WL_SW_DIR)/runtime/link.ld
HAL_SRC = $(wildcard $(WL_SW_DIR)/hal/*.c $(WL_SW_DIR)/hal/*.S)
HAL_OBJ = $(patsubst %.c, %.o, $(HAL_SRC:.S=))
RUNTIME_OBJ = $(HAL_OBJ) $(WL_SW_DIR)/runtime/crt0.o


# App sources
APPS_SRC ?= $(wildcard $(WL_SW_DIR)/apps/*.c $(WL_SW_DIR)/apps/*.S)
APPS_ELF = $(patsubst %.c, %.elf, $(APPS_SRC:.S=))

APPS_BIN_IMEM = $(patsubst %.elf, %.instr_mem.bin, $(APPS_ELF))
APPS_BIN_DMEM  = $(patsubst %.elf, %.data_mem.bin, $(APPS_ELF))
APPS_DUMP = $(patsubst %.elf, %.dump, $(APPS_ELF))

APPS_BIN_H = $(WL_SW_DIR)/apps/test_wakelet_bin.h \
			$(WL_SW_DIR)/apps/test_pixel_compare.h

all-sw: $(APPS_BIN_IMEM) $(APPS_BIN_DMEM) $(APPS_DUMP) $(APPS_BIN_H)

##################
# Snitch bootrom #
##################

BOOTROM_SRC = $(wildcard $(WL_SW_DIR)/bootrom/*.S) $(WL_SW_LIBS)
BOOTROM_CC_FLAGS = $(CC_LD_FLAGS) -Os -fno-zero-initialized-in-bss -flto -fwhole-program -march=$(MARCH) -MMD -MP

$(WL_SW_DIR)/bootrom/snitch_bootrom.bin: $(WL_SW_DIR)/bootrom/snitch_bootrom.elf $(WL_SW_DIR)/bootrom/snitch_bootrom.dump
	$(OBJCOPY) -O binary $< $@

# Priority over generic %.elf rule
$(WL_SW_DIR)/bootrom/snitch_bootrom.elf: $(WL_SW_DIR)/bootrom/snitch_bootrom.ld $(BOOTROM_SRC)
	$(CC) $(WL_SW_INCL) -T$< $(BOOTROM_CC_FLAGS) -o $@ $(BOOTROM_SRC)

###############
# Compilation #
###############

.PRECIOUS: %.elf
%.elf: $(LINKER_SCRIPT) $(RUNTIME_OBJ) $(WL_SW_LIBS) %.o
	$(CC) $(WL_SW_INCL) -T$(LINKER_SCRIPT) $(CC_LD_FLAGS) -o $@ $(filter %.o,$^) $(WL_SW_LIBS)

# If available, compile %.c source
# .PRECIOUS: %.o
%.o: %.c
	$(CC) $(WL_SW_INCL) $(CC_FLAGS) -c $< -o $@

# Otherwise, compile %.S source
%.o: %.S
	$(CC) $(WL_SW_INCL) $(CC_FLAGS) -c $< -o $@

# Generate binary dump for inspection
%.dump: %.elf
	$(OBJDUMP) -D -S $< > $@

# Linker scripts
.PRECIOUS: %.ld
%.ld: %.ld.c
	$(CC) $(WL_SW_INCL) $(WL_SW_HWDEFS) -P -E $< -o $@

##################################
# Separate binaries for flashing #
##################################

# Create binary to flash instruction memory (only .text)
%.instr_mem.bin: %.elf
	$(OBJCOPY) --only-section=.text -O binary $< $@

# Create rule for bin.h, moved from CVE2 file
$(WL_SW_DIR)/apps/test_wakelet_bin.h: $(WL_SW_DIR)/apps/test_wakelet.instr_mem.bin
	@echo "// Auto-generated by Makefile from $<. Do not edit manually." > $@
	@echo "#ifndef SNITCH_WORKLOAD_BIN_H" >> $@
	@echo "#define SNITCH_WORKLOAD_BIN_H" >> $@
	@echo "#include <stdint.h>" >> $@
	@echo "static const unsigned char snitch_workload_bin[] = {" >> $@
# Read the bin file and create an output array 
	xxd -i < $< | grep -v "^unsigned" | grep -v "^}" >> $@
	@echo "};" >> $@
# Gneerate 32 bit words 
	@echo "#define SNITCH_WORKLOAD_WORDS (sizeof(snitch_workload_bin)/4)" >> $@
	@echo "#endif" >> $@

# Create binary to flash data memory (data + rodata)
%.data_mem.bin: %.elf
	$(OBJCOPY) --only-section=.misc -O binary $< $@

$(WL_SW_DIR)/apps/test_pixel_compare.h: $(WL_SW_DIR)/apps/test_pixel_compare.instr_mem.bin
	@echo "// Auto-generated by Makefile from $<. Do not edit manually." > $@
	@echo "#ifndef SNITCH_PIXEL_COMPARE_BIN_H" >> $@
	@echo "#define SNITCH_PIXEL_COMPARE_BIN_H" >> $@
	@echo "#include <stdint.h>" >> $@
	@echo "static const unsigned char snitch_workload_bin[] = {" >> $@
	xxd -i < $< | grep -v "^unsigned" | grep -v "^}" >> $@
	@echo "};" >> $@
	@echo "#define SNITCH_WORKLOAD_WORDS (sizeof(snitch_workload_bin)/4)" >> $@
	@echo "#endif" >> $@

###########
# Helpers #
###########
# Add clean up rule for bin.h

.PHONY: clean-sw
clean-sw:
	rm -f $(LINKER_SCRIPT)
	rm -f $(WL_SW_DIR)/apps/*.{elf,bin,dump,o,d}
	rm -f $(WL_SW_DIR)/runtime/*.{o,d}
	rm -f $(WL_SW_DIR)/apps/test_wakelet_bin.h
	rm -f $(WL_SW_DIR)/apps/test_pixel_compare.h

